#Convert("/home/bnvlab2/scVI_brain/no_erythocytes/adata_subset_ages.h5ad", dest = 'h5Seurat', overwrite = T)

library(escape)
library(msigdbr)
library(Seurat)
library(dplyr)



brain_subset <- LoadH5Seurat('/home/bnvlab2/scVI_brain_organoids/no_erythocytes_atlas/brain_subset_ages_as_organoid.h5seurat',   assays    = "RNA",        # <- pick one
                             reductions = NULL, graphs = NULL, neighbors = NULL,
                             misc = FALSE, meta.data = FALSE)

pathways <- c('GOBP_AMYLOID_BETA_METABOLIC_PROCESS', 'GOBP_AMYLOID_FIBRIL_FORMATION',
            'GOBP_AMYLOID_PRECURSOR_PROTEIN_BIOSYNTHETIC_PROCESS', 'GOBP_AMYLOID_PRECURSOR_PROTEIN_CATABOLIC_PROCESS', 
            'GOBP_AMYLOID_PRECURSOR_PROTEIN_METABOLIC_PROCESS', 'GOBP_CELL_MORPHOGENESIS_INVOLVED_IN_NEURON_DIFFERENTIATION',
            'GOBP_CENTRAL_NERVOUS_SYSTEM_NEURON_AXONOGENESIS', 'GOBP_CENTRAL_NERVOUS_SYSTEM_NEURON_DEVELOPMENT', 
            'GOBP_CENTRAL_NERVOUS_SYSTEM_NEURON_DIFFERENTIATION', 'GOBP_GLIAL_CELL_APOPTOTIC_PROCESS', 'GOBP_GLIAL_CELL_PROLIFERATION', 
            'GOBP_HIPPOCAMPAL_NEURON_APOPTOTIC_PROCESS', 'GOBP_INTRINSIC_APOPTOTIC_SIGNALING_PATHWAY_IN_RESPONSE_TO_DNA_DAMAGE', 
            'GOBP_MITOTIC_G2_DNA_DAMAGE_CHECKPOINT_SIGNALING', 'GOBP_MITOTIC_INTRA_S_DNA_DAMAGE_CHECKPOINT_SIGNALING',
            'GOBP_NEGATIVE_REGULATION_OF_AMYLOID_FIBRIL_FORMATION', 'GOBP_NEGATIVE_REGULATION_OF_NOTCH_SIGNALING_PATHWAY',
            'GOBP_NEURON_APOPTOTIC_PROCESS', 'GOBP_NOTCH_RECEPTOR_PROCESSING', 'GOBP_NOTCH_SIGNALING_PATHWAY', 
            'GOBP_POSITIVE_REGULATION_OF_NOTCH_SIGNALING_PATHWAY',
             'GOBP_SIGNAL_TRANSDUCTION_IN_RESPONSE_TO_DNA_DAMAGE', 
            'GOMF_TAU_PROTEIN_BINDING', 'HP_ABNORMAL_NEURON_MORPHOLOGY', 'HP_ATROPHY_DEGENERATION_AFFECTING_THE_BRAINSTEM', ## ???
            'HP_AXONAL_DEGENERATION', 'HP_AXONAL_DEGENERATION_REGENERATION', 'HP_CEREBELLAR_MALFORMATION',## ???
            'HP_GLOBAL_BRAIN_ATROPHY', 'HP_NEURODEGENERATION',  ## ???
            'GOBP_AMYLOID_BETA_FORMATION', 'GOBP_CANONICAL_WNT_SIGNALING_PATHWAY', 
            'GOBP_CANONICAL_WNT_SIGNALING_PATHWAY_INVOLVED_IN_REGULATION_OF_CELL_PROLIFERATION',
            'GOBP_CELL_CELL_SIGNALING_BY_WNT', 'GOBP_NEGATIVE_REGULATION_OF_CANONICAL_WNT_SIGNALING_PATHWAY',
            'GOBP_NEGATIVE_REGULATION_OF_NON_CANONICAL_WNT_SIGNALING_PATHWAY', 
            'GOBP_NEGATIVE_REGULATION_OF_WNT_SIGNALING_PATHWAY', 
            'GOBP_NON_CANONICAL_WNT_SIGNALING_PATHWAY', 'GOBP_NOTCH_SIGNALING_INVOLVED_IN_HEART_DEVELOPMENT', 
            'GOBP_POSITIVE_REGULATION_OF_CANONICAL_WNT_SIGNALING_PATHWAY', 
            'GOBP_POSITIVE_REGULATION_OF_NON_CANONICAL_WNT_SIGNALING_PATHWAY', 
            'GOBP_POSITIVE_REGULATION_OF_TRANSCRIPTION_OF_NOTCH_RECEPTOR_TARGET', 'GOBP_POSITIVE_REGULATION_OF_WNT_SIGNALING_PATHWAY', 
            'GOBP_POSITIVE_REGULATION_OF_WNT_SIGNALING_PATHWAY_PLANAR_CELL_POLARITY_PATHWAY', 
            'GOBP_REGULATION_OF_CANONICAL_WNT_SIGNALING_PATHWAY', 'GOBP_REGULATION_OF_NON_CANONICAL_WNT_SIGNALING_PATHWAY', 
            'GOBP_REGULATION_OF_NOTCH_SIGNALING_PATHWAY', 'GOBP_REGULATION_OF_WNT_SIGNALING_PATHWAY',
            'GOBP_REGULATION_OF_WNT_SIGNALING_PATHWAY_PLANAR_CELL_POLARITY_PATHWAY',
            'GOBP_WNT_PROTEIN_SECRETION', 'GOBP_WNT_SIGNALING_PATHWAY_CALCIUM_MODULATING_PATHWAY',
            'GOBP_WNT_SIGNALING_PATHWAY_INVOLVED_IN_MIDBRAIN_DOPAMINERGIC_NEURON_DIFFERENTIATION',
            'GOBP_CARDIAC_CELL_FATE_COMMITMENT', 'GOBP_CELL_FATE_COMMITMENT', 
            'GOBP_CELL_FATE_DETERMINATION', 'GOBP_CELL_FATE_SPECIFICATION', 
            'GOBP_CELL_FATE_SPECIFICATION_INVOLVED_IN_PATTERN_SPECIFICATION', 'GOBP_FOREBRAIN_NEURON_FATE_COMMITMENT',
            'GOBP_FOREBRAIN_RADIAL_GLIAL_CELL_DIFFERENTIATION', 'GOBP_GLIAL_CELL_DEVELOPMENT', 'GOBP_GLIAL_CELL_DIFFERENTIATION',
            'GOBP_GLIAL_CELL_FATE_COMMITMENT', 'GOBP_GLIAL_CELL_MIGRATION', 'GOBP_NEGATIVE_REGULATION_OF_BMP_SIGNALING_PATHWAY', 
            'GOBP_NEGATIVE_REGULATION_OF_GLIAL_CELL_DIFFERENTIATION', 'GOBP_NEGATIVE_REGULATION_OF_GLIAL_CELL_PROLIFERATION', 
            'GOBP_NEURAL_CREST_CELL_DIFFERENTIATION', 'GOBP_NEURAL_CREST_CELL_FATE_COMMITMENT', 
            'GOBP_NEURAL_CREST_CELL_MIGRATION_INVOLVED_IN_AUTONOMIC_NERVOUS_SYSTEM_DEVELOPMENT',
            'GOBP_NEURAL_CREST_FORMATION', 'GOBP_NEURON_FATE_COMMITMENT', 'GOBP_NEURON_FATE_DETERMINATION', 
            'GOBP_NEURON_FATE_SPECIFICATION', 'GOBP_NEURON_GLIAL_CELL_SIGNALING', 'GOBP_POSITIVE_REGULATION_OF_BMP_SIGNALING_PATHWAY', 
            'GOBP_POSITIVE_REGULATION_OF_GLIAL_CELL_DIFFERENTIATION', 'GOBP_POSITIVE_REGULATION_OF_GLIAL_CELL_MIGRATION',
            'GOBP_POSITIVE_REGULATION_OF_GLIAL_CELL_PROLIFERATION', 'GOBP_RADIAL_GLIAL_CELL_DIFFERENTIATION',
            'GOBP_REGULATION_OF_BMP_SIGNALING_PATHWAY', 'GOBP_REGULATION_OF_GLIAL_CELL_APOPTOTIC_PROCESS', 
            'GOBP_REGULATION_OF_GLIAL_CELL_DIFFERENTIATION', 'GOBP_REGULATION_OF_GLIAL_CELL_MIGRATION', 
            'GOBP_REGULATION_OF_GLIAL_CELL_PROLIFERATION', 
             'GOBP_REGULATION_OF_MICROGLIAL_CELL_ACTIVATION', 
            'GOBP_RESPONSE_TO_BMP')

geneste_C5 <- getGeneSets(library = "C5") 

# filtered_gene_sets_C5_2 <- geneste_C5[names(geneste_C5) %in% pathways]


ES_brain <- enrichIt(obj = brain_subset,
                      gene.sets = filtered_gene_sets_C5_2,
                      groups = 1000,
                      cores=4)


write.csv(ES_brain, '/home/bnvlab2/scVI_brain/no_erythocytes/ES_brain_pathways.csv')

